services:
  - type: web
    name: astarr-music
    env: python
    region: oregon
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m ShrutiMusic
    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

      - key: API_ID
        value: "23057641"

      - key: API_HASH
        value: "4858e8a1daa57a3211103d0266271058"

      - key: API_KEY
        value: ""

      - key: BOT_TOKEN
        value: "8511575655:AAGPB_KpHvHve3d6v8QChWvM8TzQjqJR-Yc"

      - key: MONGO_DB_URI
        value: "mongodb+srv://astarrmusicbot:Sikander9898@cluster0.jskselv.mongodb.net/?appName=Cluster0"

      - key: OWNER_ID
        value: "8785619142"

      - key: OWNER_USERNAME
        value: "SIKANDER_025"

      - key: BOT_USERNAME
        value: "AstarrMusicBot"

      - key: UPSTREAM_REPO
        value: "https://github.com/NoxxOP/ShrutiMusic"

      - key: STRING_SESSION
        value: "BQFf1OkAE9d_nHv2RdW8Tnlf0uFIu16QV-MqxfbEL2eLutNzA3vU3666mAIxaUM0AF2c31WtK3M06IGpB6TZk0Ix-Lrz9ngMd2xIsQ0Jk9bNI4odWhJA8nD3PJ05gx4DuxRgQ2_yCuKw8LUg78Q22S6xvfp5xl5LpoTz0CujgmDtGFDyMGWoq7X8hqK4gfKDxBpINgxEjpaOKOWlZV5E8XfrA0kyYtNgNkN67qWUCjvJVywwRRMUSruAhYvF6w8T8zWXmHGudh3-XbcL8hPPldqyGTUr4zy7T4dXqNDwFaid-O7MfHNnK8WJtTL-4UPv8kOkop8ijkFUgE62ico2FQckzEYW8AAAAAIGJeJYAA"

      - key: LOG_GROUP_ID
        value: "-1003977469179"

      - key: SUPPORT_GROUP
        value: "https://t.me/AstarrMusicSupport"

      - key: SUPPORT_CHANNEL
        value: "https://t.me/AstarrMusicChannel"
